---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: helm
      name: tiller
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_HISTORY_MAX
          value: "200"
        - name: TILLER_TLS_VERIFY
          value: "1"
        - name: TILLER_TLS_ENABLE
          value: "1"
        - name: TILLER_TLS_CERTS
          value: /etc/certs
        image: gcr.io/kubernetes-helm/tiller:v2.14.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        - containerPort: 44135
          name: http
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
        volumeMounts:
        - mountPath: /etc/certs
          name: tiller-certs
          readOnly: true
      serviceAccountName: tiller
      volumes:
      - name: tiller-certs
        secret:
          secretName: tiller-secret
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  ports:
  - name: tiller
    port: 44134
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVXVENDQTBHZ0F3SUJBZ0lKQUl5T1V4a1RiclBXTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUhDTVFzd0NRWUQKVlFRR0V3SlZVekVMTUFrR0ExVUVDQXdDVFVReEZUQVRCZ05WQkFjTURFOTNhVzVuY3lCTmFXeHNjekVWTUJNRwpBMVVFQ2d3TVVFRlBVMGxPSUV4UFEwRk1NVUV3UHdZRFZRUUxERGhRUVU5VFNVNElDQWdJQ0FoSlZCdGJNMzRiCld6TitHMXN6Zmh0YlF4dGJReHRiUXh0YlF4dGJRd2dJQ0FnSUNBaFFUd2hCVDFOSlRqRVZNQk1HQTFVRUF3d00KVUVGUFUwbE9JRXhQUTBGTU1SNHdIQVlKS29aSWh2Y05BUWtCRmc5bVpXMXBRSEJoYjNOcGJpNWpiMjB3SGhjTgpNVGd3T1RFeU1UWXhOakUxV2hjTk1qTXdPVEV4TVRZeE5qRTFXakNCd2pFTE1Ba0dBMVVFQmhNQ1ZWTXhDekFKCkJnTlZCQWdNQWsxRU1SVXdFd1lEVlFRSERBeFBkMmx1WjNNZ1RXbHNiSE14RlRBVEJnTlZCQW9NREZCQlQxTkoKVGlCTVQwTkJUREZCTUQ4R0ExVUVDd3c0VUVGUFUwbE9DQWdJQ0FnSVNWUWJXek4rRzFzemZodGJNMzRiVzBNYgpXME1iVzBNYlcwTWJXME1JQ0FnSUNBZ0lVRThJUVU5VFNVNHhGVEFUQmdOVkJBTU1ERkJCVDFOSlRpQk1UME5CClRERWVNQndHQ1NxR1NJYjNEUUVKQVJZUFptVnRhVUJ3WVc5emFXNHVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNFJkbklXUG9YalZqMWV6TkNqNUpMc3UvLy9yU2Z6TmJyTzR6MlVkRQphWnFkODNkTjB2ZlVXN1FwMHJ0K2dzYm9qUzYrZDZDeStLQ0kyL0lKblhUZkxPOU4zZjNtQzlyRkh1amNBK1BSCm0vamE0Y0RkV0hFRjd2d2RwaldzTnVBYzQ1MVJwM3lxNHFJQWMyc21sYnM4ZVVKQ2hJWlU0K3I1Y3VkTlQwUkEKWXF6eHVEZUZ5TElpWVYzYUJKdFJVeWFkUmhUOUVVWU96dTFLQi9rUGpqSkpNNWVxZEtSdFZUYWZ3MThVeXlJWApBeTZUTGdubmQ2NTRvOCtBZTJJanJ4a0UvNmN1dVFxWDJhUFlneUNVcERZNnMzRDBmemw0Q0w0NUl5TGljYjBECmh0dmQ2TEl4QmtWako5Q2NtMUxUa21rTFN3Ti8xVEZSUEErdGVKdGF1Y1dVWVFJREFRQUJvMUF3VGpBZEJnTlYKSFE0RUZnUVU1VktHcjh3SzdXZE13Z3RreGZnd3ppTkFneVV3SHdZRFZSMGpCQmd3Rm9BVTVWS0dyOHdLN1dkTQp3Z3RreGZnd3ppTkFneVV3REFZRFZSMFRCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF6RTloClZBZ2JBS3VxaHV6VkVJOWpvVEl5Y2JFczJRdnlrVitpQzcxcGFJa1FqaUR0OFJSSFdaZUZmMHByZHFFeTlJU0YKTjVxTFBmZmx1NkhSa2hPNDdTdy9TZHlTelVrQTJSaUVuVVJpNTR5cWJJOHhzWUlOM01NeUpudVorbmQrdFNFTwo2cVUrUGVqMzBSVFdnQmhmeGV1SksrL1J3SFBFM1dqWGZvSDBFamwvUEk4WEphWU1TL0FQUmFXL01MVnZlM0E2Cm9ub0hSYitIdEZjNTJXZkd1VDZldXdlL21XOHRCOXFtUHllRExUbEF4eUdjWGR3VzYwL2c4N3dzYzc5akpIdFkKN2hzVDl5ekQvZjZOb0UwMTNFSm5iZ2tXRFlWSzBVZGo3a3ZKVVpITGJxV0V6WklYWWFqNExXV2dHZStOQlY2Zgp5ZlZXZG1KU2lKVnk3V0NsRUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVIakNDQXdhZ0F3SUJBZ0lKQUs5Y2hkSlJkaXB5TUEwR0NTcUdTSWIzRFFFQkN3VUFNSUhDTVFzd0NRWUQKVlFRR0V3SlZVekVMTUFrR0ExVUVDQXdDVFVReEZUQVRCZ05WQkFjTURFOTNhVzVuY3lCTmFXeHNjekVWTUJNRwpBMVVFQ2d3TVVFRlBVMGxPSUV4UFEwRk1NVUV3UHdZRFZRUUxERGhRUVU5VFNVNElDQWdJQ0FoSlZCdGJNMzRiCld6TitHMXN6Zmh0YlF4dGJReHRiUXh0YlF4dGJRd2dJQ0FnSUNBaFFUd2hCVDFOSlRqRVZNQk1HQTFVRUF3d00KVUVGUFUwbE9JRXhQUTBGTU1SNHdIQVlKS29aSWh2Y05BUWtCRmc5bVpXMXBRSEJoYjNOcGJpNWpiMjB3SGhjTgpNVGt4TURFNE1ETXhNak01V2hjTk1qUXhNREUyTURNeE1qTTVXakNCaVRFTE1Ba0dBMVVFQmhNQ1ZWTXhDekFKCkJnTlZCQWdNQWsxRU1SVXdFd1lEVlFRSERBeFBkMmx1WjNNZ1RXbHNiSE14RlRBVEJnTlZCQW9NREZCQlQxTkoKVGlCTVQwTkJUREVQTUEwR0ExVUVDd3dHUkVWV1QxQlRNUTh3RFFZRFZRUUREQVowYVd4c1pYSXhIVEFiQmdrcQpoa2lHOXcwQkNRRVdEbmx2ZFhKQVpXMWhhV3d1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTF2b2hQOHZRTVZFNGc2MUQ2VEFOejlDZGVpTlhlQ2pEM2djUkh6SEJTWU5OUnFIYjRNVFQKTERNY3lsY3NYTTI3djdXUE8yRGUvT21SdzdGc2pTdnl3R2JHTWFpRklzdEFhTWRTUUlDNXJJeERLenpLNndWVApwNFpUc1lScXEyUWZmYUxDY3NhUmVaSHQrZkN3UDV6OUMxVEk4MFIvN1ViOEZRaXVMQm1pNjZWeG1CY3gxV0tsCmpvQW9YdlBGbFRPZEVtTUNId3JSd3BrVHRtTmtMVEMvTXNXS1ROdWFzdjNHZFl2TnJySFBwcnBQaFlqYlR1WEwKMUVnRnhjK0tXVU9GME5vYlVHUHVzcWRGT3orNStPbE10VUtUemxLL2dKU0RnU3djS0FBS3ByYjdKSktzeVp1TApkWU1laUs5clZkbkMraE5EK1pQL1E1SlN3RS9reTlEU3V3SURBUUFCbzA0d1REQWZCZ05WSFNNRUdEQVdnQlRsClVvYXZ6QXJ0WjB6Q0MyVEYrRERPSTBDREpUQUpCZ05WSFJNRUFqQUFNQXNHQTFVZER3UUVBd0lFOERBUkJnTlYKSFJFRUNqQUlnZ1owYVd4c1pYSXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ3ZLK254dUs0ZEc0SVh2VFFFUwpXY1JlT0s2Qk9vOWVUa2o0MFhxcE1sUGtnSVFUb25UZkd3b2kvY1pHRlFSMmlZWkJMSlVya3pjWXNDYjc4VzVDCnRTMG94YXRnSnFmM0xLRHNUeXZWWXNLbkVmaHg2bDFoMEwzbU5KVUhJVjJXRk00YW9JbjAvVGlJRlVFYm1OMTEKU252SU5SdnY3amppbHk5T3YrcEFicXBBMlRWNzNNZ091cmRVK01LQlpsUlRHeGpuZ2dhMS8zYUxGV0VjaHgrVQpwenZ2OTNmRzkwZDdzOTVTWlY3eXlLd3dqcFNRM0lTUjRPdHV4K3ZDeXJVdXlmMlBYZk1YUDM1ejlhd0J6M0hjClh1aGpPcWs1aWtZNXRTcURvL2FMWjRBVTR0RllRTkhXSkdvVzI4SXhCTWpoNnBqdStlUW5TbzUrSWd1dGdDU2gKci9zPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFcraUUveTlBeFVUaUQKclVQcE1BM1AwSjE2STFkNEtNUGVCeEVmTWNGSmcwMUdvZHZneE5Nc014ektWeXhjemJ1L3RZODdZTjc4NlpIRApzV3lOSy9MQVpzWXhxSVVpeTBCb3gxSkFnTG1zakVNclBNcnJCVk9uaGxPeGhHcXJaQjk5b3NKeXhwRjVrZTM1CjhMQS9uUDBMVk1qelJIL3RSdndWQ0s0c0dhTHJwWEdZRnpIVllxV09nQ2hlODhXVk01MFNZd0lmQ3RIQ21STzIKWTJRdE1MOHl4WXBNMjVxeS9jWjFpODJ1c2MrbXVrK0ZpTnRPNWN2VVNBWEZ6NHBaUTRYUTJodFFZKzZ5cDBVNwpQN240NlV5MVFwUE9VcitBbElPQkxCd29BQXFtdHZza2txekptNHQxZ3g2SXIydFYyY0w2RTBQNWsvOURrbExBClQrVEwwTks3QWdNQkFBRUNnZ0VBY0hua1JZMnNldkVrNFhnWTdQdVFibWVXelIyS21UcXk2QXJJZ1lxMXQzRzAKVDcxRjNuNzhnY2FvVEpGNWk0QzB0NlFWc1pxSWNNai8wK1NUaC9VemlFajliMlBkYkl2dFFpVHZPd0plb3hHcgozd1pxb0xaancyVzdpa2hleXhlU2hsaE81bUJRSXN3Z044SWZaTmtOYUExUEtrQnZza1NPaGE3SitoYmJyL0FrCjlXV3AwV0NXYkhNb0tMcTRBVkJqaFBYVG53Q0R3TXNFS0FMb2oyZHZ0c1dtclZRbHkrMFZ1eUxYS0hyaGhCVnUKOW5Nb01Bc1RsdFZzTTRodUpTWGl2aWFXREo4d2pCL283N2w3RXVwM29jL3hkUGZJcVh6VDQzYUFubEhOYUpEOApoSEFyRkxleS9HRTA5UnJBT1ZySDJoSVVYQndwcCsraXdaUC9PclhES1FLQmdRRDRIK2JzNmVQYTkxZnNBM0JtCng1amJxdkhZT3RiTzhZT2pET1JSM1pSbWZHRWFsTHBKMHI0b1Y2MWpra0QrWXpMQ0xmem9Nbjg2YXV3Z1BXaGYKR0xCTTVUWXNITG90c3Q3NzVYVStUZVNiN1hsc093bndnSDUzNDNKRnhTMWNXNUQ3OWQ0OUJaOTgzRHhhK3YzbQpaTE1tUVJZSkdEU1ljSCtJaTQ1T2dldGsvUUtCZ1FEZHpPU0F6ZEtUWlBkNmd5cHVNTEozOVhxcndXVlpDOUh5CndZOER1RjJTYWszWk9tMWU0YXptT29pbW9wcUI0T3RxbE5WeWVvT3o4VGQvOVhuUVY2NlYrN2cxM1pCZ09SLzcKSjRkZmhxSDR2aHp4WlVVYnRnRmF1d3F6VjVrM3FnOWpwL0pleUFoa214eVNQdnRxTXJ0UlJkZWl2c2xXZVN4Mwpzc0RoRmJIQUZ3S0JnRGcwR2IzZWVRTjNkWTM3ZFhHQ2tzaG5YMkxJYVRIMUdRbE0rVWJsOXlDRDJnY0lXMjR2CmMyMTE5c3VRTEhLekM2TmFnV2dqVUJodWNkQVh1TldacFEyMStlQmlIWFlPaDEzdHF2SVMrTTZ0S3d6dURxRlEKcWRVRVN6VXNwY3ErM3dlRHVQUi9tcEhRM1VjS2hZcXprclQrbHp3MkpHdkhSOHdwT0hIbUVla05Bb0dCQUxHLwpDVC9Qc2ZrODZMYmRkcHRubXg1WE16K0JkTjZ2Z2tpd3BST3VKQTY1OGprcmdZcVFBQ2Rnc1RJWkRRa1lYcEREClJXckFrOXNZYkFtM2h5OVhsU25NMkFzU3pDalFucmgvTFJWNHAwVFgxZ245eGl3MjUwNzJwZFNqVnI0dElyZ1MKVjBGdHZJd2pZZm94VHZvRVBla2J0M3RNdWJ6NnpvLytTR1FaSnFGeEFvR0FUWmRLc1FGWWNtNDl5RERCdkhBdQpaMHdGMHBsMWtPMjRER0ZxSTk2WnRBZHIxWG5jb3hXTllRYXN0R0pDMEJwTUJ6VlFvTEJtNFp6T0pYWm1KUXZzClRHanU0a3pSU1JPMUUzNnZoYVFMUmNjVEs1c0c2K0ZiS09vRTN1RXJZa2R6aU03Z3FDOVcwMEQwQWs3c1IraSsKR295eG9GR0pGMEJ2aVI1TEtyK090M0U9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-secret
  namespace: kube-system
type: Opaque

...
