apiVersion: v1
data:
  install-requirements.sh: |
    #!/bin/sh -e
    if [ ! -d /dags ]; then
      echo "No folder /dags"
      exit 0
    fi
    cd /dags
    if [ -f requirements.txt ]; then
      pip install --user -r requirements.txt
    else
      exit 0
    fi
kind: ConfigMap
metadata:
  creationTimestamp: "2019-11-11T03:14:12Z"
  labels:
    app: airflow
    chart: airflow-4.1.2
    heritage: Tiller
    release: airflow
  name: airflow-scripts
  namespace: airflow
  resourceVersion: "4422860"
  selfLink: /api/v1/namespaces/airflow/configmaps/airflow-scripts
  uid: 42b3abc9-04f7-43ce-bc44-2274660b1a7a
