apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
spec:
  capacity:
    storage: 1Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below 
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.10.10.55
    path: /SHARE/DAGS/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-dags
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: airflow-dags
---
